--- #YAML:1.0
name:               Net-IMP
version:            0.627
abstract:           Inspection and Modification Protocol to interface with proxies, IDS...
author:
    - Steffen Ullrich <sullr@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
resources:
    bugtracker:  https://rt.cpan.org/Dist/Display.html?Queue=Net-IMP
    homepage:    https://github.com/noxxi/p5-net-imp
    license:     http://dev.perl.org/licenses/
    repository:  https://github.com/noxxi/p5-net-imp
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
